language: node_js

node_js:
  - "stable"

install: npm install

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE property" -U postgres
  - npm i
  - npm run createTables
  
script:
  - npm run test

after_success: 
- npm run coveralls

notifications:
  email: false